package com.ecillie.fbomanager.platform.api;

/** Trusted application capabilities supplied by the identity boundary. */
public enum Capability {
	ADMINISTRATION_READ, ADMINISTRATION_WRITE, AIRCRAFT_READ, AIRCRAFT_WRITE, PARKING_READ, PARKING_WRITE, VISITS_READ, VISITS_WRITE, SERVICES_READ, SERVICES_WRITE, FLEET_READ, FLEET_WRITE, FUEL_READ, FUEL_WRITE, WORKFORCE_READ, WORKFORCE_WRITE, TASKS_READ, TASKS_WRITE, OPERATIONS_READ
}
